name: Deploy Python App

on:
  push:
    branches:
      - main   # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout Code
        uses: actions/checkout@v3

      - name: ðŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ðŸ“¦ Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: ðŸ” SSH into Server & Run App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/myapp
            git pull origin main
            pip3 install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > output.log 2>&1 &
